backend:
  name: git-gateway
  branch: main  # Ganti dengan nama branch GitHub kamu (biasanya 'main' atau 'master')

media_folder: "img"
public_folder: "/img"

collections:
  - name: "galeri"
    label: "Galeri Foto"
    folder: "img"
    create: true
    slug: "{{slug}}"
    media_folder: ""
    public_folder: ""
    fields:
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Gambar", name: "image", widget: "image"}
